require_relative 'config/environment'

desc "Loads a console"
task :console do
    Pry.start
end

desc "say hello"
task :say_hi do
    puts "What's up 1119?"
end

desc "create book table"
task :make_book_table do

    # HEREDOC
    sql = <<-SQL 
        CREATE TABLE IF NOT EXISTS books (
        id INTEGER PRIMARY KEY,
        title VARCHAR(255),
        author_id INTEGER
    );
    SQL
    DB.execute(sql)
end


desc "create author table"
task :make_author_table do 

    sql_statement = <<-SQL
    CREATE TABLE IF NOT EXISTS authors (
    id INTEGER PRIMARY KEY,
    name VARCHAR(255)
);
SQL
    DB.execute(sql_statement)

end